# Generated by Django 4.2.1 on 2023-06-10 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePreprocessing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_preprocessing', models.ImageField(upload_to='static/images/preprocessing/')),
                ('image_ground_truth', models.ImageField(upload_to='static/images/ground_truth/')),
                ('resize', models.BooleanField(default=False)),
                ('resize_width', models.IntegerField(blank=True, null=True)),
                ('resize_height', models.IntegerField(blank=True, null=True)),
                ('grayscale', models.BooleanField(default=False)),
                ('blur', models.BooleanField(default=False)),
                ('blur_radius', models.IntegerField(blank=True, null=True)),
                ('sharpen', models.BooleanField(default=False)),
                ('sharpen_radius', models.IntegerField(blank=True, null=True)),
                ('sharpen_percent', models.IntegerField(blank=True, null=True)),
                ('brightness', models.BooleanField(default=False)),
                ('brightness_percent', models.IntegerField(blank=True, null=True)),
                ('contrast', models.BooleanField(default=False)),
                ('contrast_percent', models.IntegerField(blank=True, null=True)),
                ('smooth', models.BooleanField(default=False)),
                ('smooth_radius', models.IntegerField(blank=True, null=True)),
                ('edge_enhance', models.BooleanField(default=False)),
                ('edge_enhance_radius', models.IntegerField(blank=True, null=True)),
                ('find_edges', models.BooleanField(default=False)),
                ('find_edges_radius', models.IntegerField(blank=True, null=True)),
                ('contour', models.BooleanField(default=False)),
                ('contour_radius', models.IntegerField(blank=True, null=True)),
                ('enhance', models.BooleanField(default=False)),
                ('enhance_percent', models.IntegerField(blank=True, null=True)),
                ('colorize', models.BooleanField(default=False)),
                ('colorize_color', models.CharField(blank=True, max_length=20, null=True)),
                ('posterize', models.BooleanField(default=False)),
                ('posterize_bits', models.IntegerField(blank=True, null=True)),
                ('solarize', models.BooleanField(default=False)),
                ('solarize_threshold', models.IntegerField(blank=True, null=True)),
                ('invert', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.image')),
            ],
        ),
    ]
