# Generated by Django 4.2.1 on 2023-06-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_imagepreprocessing'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepreprocessing',
            name='resize_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
