# Generated by Django 4.2.1 on 2023-06-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_imagepreprocessing_resize_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepreprocessing',
            old_name='blur',
            new_name='gaussian_filter',
        ),
        migrations.RenameField(
            model_name='imagepreprocessing',
            old_name='blur_radius',
            new_name='gaussian_filter_size',
        ),
        migrations.RenameField(
            model_name='imagepreprocessing',
            old_name='colorize',
            new_name='mean_filter',
        ),
        migrations.RenameField(
            model_name='imagepreprocessing',
            old_name='contour_radius',
            new_name='mean_filter_size',
        ),
        migrations.RenameField(
            model_name='imagepreprocessing',
            old_name='contour',
            new_name='median_filter',
        ),
        migrations.RenameField(
            model_name='imagepreprocessing',
            old_name='edge_enhance_radius',
            new_name='median_filter_size',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='colorize_color',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='edge_enhance',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='enhance',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='enhance_percent',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='find_edges',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='find_edges_radius',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='grayscale',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='invert',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='posterize',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='posterize_bits',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='sharpen',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='sharpen_percent',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='sharpen_radius',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='smooth',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='smooth_radius',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='solarize',
        ),
        migrations.RemoveField(
            model_name='imagepreprocessing',
            name='solarize_threshold',
        ),
    ]
