# Generated by Django 4.2.1 on 2023-06-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_blur_imagepreprocessing_gaussian_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepreprocessing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='imagepreprocessing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
