# Generated by Django 4.2.1 on 2023-06-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_imagepreprocessing_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_segmented', models.ImageField(upload_to='static/images/segmented/')),
                ('segmentation_type', models.CharField(blank=True, max_length=255, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('k_means_score', models.FloatField(blank=True, null=True)),
                ('rand_score', models.FloatField(blank=True, null=True)),
                ('jaccard_score', models.FloatField(blank=True, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('psnr', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('image_preprocessing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentations', to='myapp.imagepreprocessing')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentationResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_results', to='myapp.image')),
                ('segmentations', models.ManyToManyField(to='myapp.segmentation')),
            ],
        ),
    ]
