# Generated by Django 4.2.1 on 2023-06-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_segmentation_segmentationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentationresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentationresult',
            name='segmentation_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='segmentationresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
