# Generated by Django 4.2.1 on 2023-06-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_segmentation_k_means_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentationresult',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
