# Generated by Django 4.2.1 on 2023-06-28 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_segmentationresult_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentationresult',
            name='segmentations',
        ),
        migrations.AddField(
            model_name='segmentationresult',
            name='preprocessing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_results', to='myapp.imagepreprocessing'),
        ),
        migrations.AddField(
            model_name='segmentationresult',
            name='segmentation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_results', to='myapp.segmentation'),
        ),
    ]
