# Generated by Django 4.2.1 on 2023-06-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_segmentationresult_segmentations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segmentationresult',
            old_name='segmentation',
            new_name='segment',
        ),
    ]
